Company & section search inputs on content pages.
parameter1/ac-business-media-websites pull request #269
Opened 2021-03-03 14:05 UTC by B77Mills

Add ability to search by company name & section name on content landing pages.  Currently this requires algolia for company search and an array of section ids. The array of ids is set on the site config as sectionSearchIds: [],

<img width="1244" alt="Screen Shot 2021-03-03 at 8 02 37 AM" src="https://user-images.githubusercontent.com/3845869/109816872-db848b00-7bf6-11eb-99d5-2b6a68f23197.png">
<img width="1158" alt="Screen Shot 2021-03-03 at 8 02 29 AM" src="https://user-images.githubusercontent.com/3845869/109816881-dd4e4e80-7bf6-11eb-93d7-12dbd0448677.png">

2021-03-07 17:37 UTC, zarathustra323 requested changes

2021-03-07 17:37 UTC, zarathustra323 commented on packages/common/package.json
> +    "@parameter1/base-cms-marko-web-theme-default": "^2.5.0",
It looks like there are some newer versions of the @parameter/base-cms dependencies. While they probably aren't needed for this PR, since you're doing an upgrade you might as well upgrade again to get the latest versions

2021-03-08 17:43 UTC, solocommand requested changes

2021-03-08 17:43 UTC, solocommand commented on docker-compose.yml
> +      ALGOLIA_DEFAULT_INDEX: ${ALGOLIA_DEFAULT_INDEX}
Add these to `x-env-defaults` at the top to reduce clutter

2021-03-08 17:43 UTC, solocommand commented on packages/common/components/marko.json
> +    "@default-index": "string"
You're not using these values in the component (you're reading from the middleware injected values instead), nor are you passing them with the call from the company content template. Update the component to use the provided values or remove them from the component definition please!

2021-03-08 17:43 UTC, solocommand commented on packages/common/components/section-search.marko
> +    params={ includeIds: sectionIds, limit:100, queryFragment: categorySectionsFragment }
```suggestion
    params={ includeIds: sectionIds, limit: 100, queryFragment: categorySectionsFragment }
```

2021-03-08 17:43 UTC, solocommand commented on packages/common/components/section-search.marko
> +$ const sectionIds = getAsArray(site, 'config.sectionSearchIds');
Use double quotes in marko files

2021-03-08 17:43 UTC, solocommand commented on packages/common/graphql/fragments/sections-search.js
> +  fullName
You're not using this field anywhere, no need to return it.

2021-03-09 18:28 UTC, brandonbk approved these changes

2021-03-09 18:28 UTC, merged