Add Featured Companies in this Article block
parameter1/ac-business-media-websites pull request #298
Opened 2021-05-17 12:42 UTC by B77Mills

Add Featured Companies in this Article block to content landing pages.  Company needs to be set in the relatedTo field of content to appear here.

<img width="630" alt="Screen Shot 2021-05-17 at 7 41 21 AM" src="https://user-images.githubusercontent.com/3845869/118490270-613ab180-b6e3-11eb-8199-1e03d3af289b.png">

2021-05-18 16:07 UTC, solocommand requested changes

2021-05-18 16:07 UTC, solocommand commented on packages/refresh-theme/components/blocks/featured-companies.marko
> +                  ...(node.website && { href: node.website, target: "_blank" }),
@B77Mills can you confirm that this is supposed to link offsite to the company webpage instead of the internal (canonical) company page?

2021-05-18 19:44 UTC, B77Mills commented on packages/refresh-theme/components/blocks/featured-companies.marko
> +                  ...(node.website && { href: node.website, target: "_blank" }),
@solocommand  I update it to point at the internal page instead of the company's website.  Also removed that field from the fragment.  We should be good to go.

2021-05-18 21:13 UTC, solocommand requested changes

2021-05-18 21:13 UTC, solocommand commented on packages/refresh-theme/components/blocks/featured-companies.marko
> +                  ...(node.cononicalPath && { href: node.cononicalPath, target: "_blank" }),
This should read `canonicalPath` not `cononicalPath`

2021-05-18 21:13 UTC, solocommand commented on packages/refresh-theme/components/blocks/featured-companies.marko
> +                  ...(node.cononicalPath && { href: node.cononicalPath, target: "_blank" }),
Also, is this the correct field? I thought it was under the `siteContext` field, is this the same as used elsewhere?

2021-05-19 12:20 UTC, B77Mills commented on packages/refresh-theme/components/blocks/featured-companies.marko
> +                  ...(node.cononicalPath && { href: node.cononicalPath, target: "_blank" }),
@solocommand  good catch on both.  I fixed the spelling error & update the link that is set.

2021-05-19 14:44 UTC, solocommand approved these changes

2021-05-19 14:45 UTC, merged