Remove sticky leaderboard from bottom of GIP
parameter1/ac-business-media-websites pull request #299
Opened 2021-05-17 13:01 UTC by Shinsina

Lower sticky leaderboard ad no longer present. 
<img width="1791" alt="Screen Shot 2021-05-17 at 8 00 19 AM" src="https://user-images.githubusercontent.com/46794001/118492798-ffc81200-b6e5-11eb-9d71-35c8c07bccfd.png">

2021-05-17 13:01 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove Sticky Leader on GIP](https://trello.com/c/DZ6rfog9/36-remove-sticky-leader-on-gip)

2021-05-17 14:07 UTC, zarathustra323 requested changes

2021-05-17 14:07 UTC, zarathustra323 commented on sites/greenindustrypros.com/config/gam.js
> -        'lb-sticky-bottom': 'default/lb1',
I'm assuming you're receiving warning messages in your server-side terminal now that these ad units are removed? Specifically `Unable to render sticky leaderboard: no path was provided.`

You'll likely want to add some wrapping logic in `packages/refresh-theme/components/fixed-ad-bottom.marko` to check for the existence of the ad unit path and only render the `<marko-web-gam-fixed-ad-bottom>` component if it's present. In other words, wrap the component call in an `<if>` block.

2021-05-18 16:02 UTC, solocommand approved these changes

2021-05-18 16:02 UTC, merged