Update spec guides to use new google docs v4 api
parameter1/ac-business-media-websites pull request #325
Opened 2021-08-17 17:40 UTC by B77Mills

- Add new spec-guide fetch route(__sec-guide?src=${sheetSrc}) that retrieves sheet data with api key set
 - Add table component logic to handle new data format.  Previously each row would have come back with `gsx$${key}.$t: value` array. Now it just returns an array of values.  I added logic to key each row off of row one column header. line 400-408 in packages/common/browser/spec-guide/table.vue 
 - Update FCP & OEM spec guide configs sheet src

2021-08-17 19:19 UTC, solocommand requested changes

2021-08-17 19:19 UTC, solocommand commented on packages/common/browser/spec-guide/table.vue
```js
const rows = unKeyed.map((row) => sheetKeys.reduce((obj, key, index) => ({ [key]: row[index] }), {}))
```

2021-08-17 19:19 UTC, solocommand commented on packages/common/spec-guide/index.js
> +      res.send(error);
Send a 500 statusCode in this case

2021-08-17 19:23 UTC, solocommand requested changes

2021-08-17 19:23 UTC, solocommand commented on docker-compose.yml
> +  GOOGLE_DOC_API_KEY: ${GOOGLE_DOC_API_KEY-(unset)}
Can you name this `SPEC_GUIDE_DOCS_API_KEY` instead

2021-08-18 13:51 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Spec guide errors](https://trello.com/c/it2OQYEW/79-spec-guide-errors)

2021-08-18 16:04 UTC, solocommand requested changes

2021-08-18 16:04 UTC, solocommand commented on packages/common/spec-guide/index.js
> +const { SPEC_GUIDE_DOCS_API_KEY } = process.env;
This should pull from envalid, not the process env directly.
```suggestion
const fetch = require('node-fetch');
const { SPEC_GUIDE_DOCS_API_KEY } = require('../env');

```

2021-08-18 16:22 UTC, solocommand approved these changes

2021-08-18 16:30 UTC, merged