Update content page company search to use elastic vs algolia
parameter1/ac-business-media-websites pull request #356
Opened 2021-11-10 15:34 UTC by B77Mills

- add new __company-search route to use with this new component.
  -- as you type in the search input it will do a call to /__company-search?searchQuery=${input} and return the base brows object back
 - remove use of algolia search.
<img width="1136" alt="Screen Shot 2021-11-10 at 9 20 17 AM" src="https://user-images.githubusercontent.com/3845869/141141193-c1d8f98a-024c-457f-bf2c-1766527bc15e.png">

2021-11-15 16:07 UTC, zarathustra323 requested changes

2021-11-15 16:07 UTC, zarathustra323 commented on packages/common/company-search/index.js
> +  app.use('/__company-search', asyncRoute(async (req, res) => {
Use the `jsonErrorHandler` middleware here and remove the try/catch... if there's an error it will automatically be caught by the json handler and return the response in JSON (so the client doesn't break)

2021-11-15 16:07 UTC, zarathustra323 commented on packages/common/browser/company-search.vue
> +      return searchCompanies(input);
This actually isn't debouncing anything, just preventing the search until there are three characters

2021-11-15 16:07 UTC, zarathustra323 commented on packages/common/browser/company-search.vue
> +  return new Promise((resolve) => {
No need to return a promise manually here, just make this an `async` function and then use awaits.

2021-11-16 17:32 UTC, B77Mills commented on packages/common/browser/company-search.vue
> +  return new Promise((resolve) => {
@zarathustra323 I made the changes we talked about, but hoping you can re-review when you have a sec.

2021-11-22 16:09 UTC, zarathustra323 approved these changes

2021-11-22 16:09 UTC, merged