Add ```publicationIds``` to site configs for FL and SDCE use for /magazine page.
parameter1/ac-business-media-websites pull request #374
Opened 2022-02-02 16:38 UTC by Shinsina

<img width="1920" alt="Screen Shot 2022-02-02 at 10 30 24 AM" src="https://user-images.githubusercontent.com/46794001/152197053-43f56655-4fc0-47cf-8d75-67859ee62562.png">
<img width="1920" alt="Screen Shot 2022-02-02 at 10 30 37 AM" src="https://user-images.githubusercontent.com/46794001/152197065-aa66e21f-9f2d-484a-b672-63b3ca25b5e1.png">

2022-02-02 16:39 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [SDC/FLOG Merge Bugs/Changes](https://trello.com/c/VoC1dLo0/163-sdc-flog-merge-bugs-changes)

2022-02-02 22:00 UTC, solocommand requested changes
To keep consistent with other sites, key these values underneath a `magazines` property.
https://github.com/parameter1/allured-business-media-websites/blob/master/sites/cosmeticsandtoiletries.com/config/site.js#L58

2022-02-03 13:56 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [SCN: Magazine pages should show individual brands](https://trello.com/c/Iycuvq2Q/165-scn-magazine-pages-should-show-individual-brands)

2022-02-03 15:30 UTC, jwade1327 approved these changes

2022-02-03 15:30 UTC, merged