Add autoSignup for newsletters onAuthenticationSuccess
parameter1/ac-business-media-websites pull request #463
Opened 2022-11-16 20:05 UTC by B77Mills

Add onAuthenticationSuccessFormatter function to auto sign users up to site specific newsletter if they do not already have a subscription for that deploymentProduct.

### FCP
```json
{
  "Description": "FCP Headline News",
  "Id": 4303,
  "AlternateId": "08",
  "StatusCode": 1,
  "Name": "FCP Headline News"
},

```
### FL
```json
{
  "Description": "FL Cold Chain Insights",
  "Id": 5218,
  "AlternateId": "11",
  "StatusCode": 1,
  "Name": "FL Cold Chain Insights"
},

```
### GIP
```json
{
  "Description": "GIP The PRO Report",
  "Id": 10020,
  "AlternateId": "AC",
  "StatusCode": 1,
  "Name": "GIP The PRO Report"
},

```
### OOH
```json
{
  "Description": "OOH Industry News eNL",
  "Id": 5638,
  "AlternateId": "47",
  "StatusCode": 1,
  "Name": "OOH Industry News eNL"
},

```
### SDCE
```json
{
  "Description": "SDCE Global Supply Chain Insights",
  "Id": 5125,
  "AlternateId": "11",
  "StatusCode": 1,
  "Name": "SDCE Global Supply Chain Insights"
},
```

2022-11-16 20:06 UTC, B77Mills commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the ability to auto signup user to daily newsletter onAuthenticationSucessHook](https://trello.com/c/VkKyxn9n/313-add-the-ability-to-auto-signup-user-to-daily-newsletter-onauthenticationsucesshook)

2022-11-18 15:33 UTC, solocommand requested changes

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +    if (!req.$omedaGraphQLClient) return payload;
This should use the omeda package's `omedaGraphQLClientProp` config: https://github.com/parameter1/base-cms/blob/master/packages/marko-web-omeda/index.js#L9

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +          && namespace.tenant === omeda.brandKey);
Use the `omedaConfig` that is already passed to this file.

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +    const omeda = req.app.locals.site.getAsObject('omeda');
Remove

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +    const identityXOptInHooks = req.app.locals.site.getAsObject('identityXOptInHooks');
Pass the hook definitions to this config factory directly from the site omeda+idx config. No need to re-retrieve the site config within the function, just adding complexity.
```
configure({
  // ...
  autoSignupDeploymentTypes: [1234, 2345],
});

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +    if (identityXOptInHooks.onAuthenticationSuccess) {
Clean up your tree; return the payload if there are no hooks to apply logic for instead of nesting the if.

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +      }
Payload should always be returned here, and the parens are not necessary.
```suggestion
      return {
        ...payload,
        ...(deploymentTypes.length && { deploymentTypes }),
      };
```

2022-11-18 15:33 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +      });
Return immediately if there's no omeda customer

```suggestion
      });
      if (!omedaCustomer) return payload;
```

2022-11-18 19:34 UTC, solocommand requested changes

2022-11-18 19:34 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +      if (!omedaConfig.omedaGraphQLClientProp || !onAuthenticationSuccess) return payload;
The `omedaGraphQLClientProp` config has a default value and ~is~ _should be_ required when configuring the Omeda package. If the value isn't specified, this will properly return, but if an incorrect value is specified (such as `ogqlv2` when no middleware sets it) or the Omeda package isn't correctly configured, this won't be correct.

What you actually want to check that the GraphQL client can be found based on the config prop path, so you should check that the value returned from the request object isn't falsey:

```suggestion
      const omedaGraphQLClient = req[omedaConfig.omedaGraphQLClientProp];
      if (!omedaGraphQLClient || !onAuthenticationSuccess) return payload;
```

2022-11-18 19:34 UTC, solocommand commented on packages/refresh-theme/config/omeda-identity-x.js
> +        omedaGraphQLClient: req[omedaConfig.omedaGraphQLClientProp],
If you define this above, you can just pass it through here
```suggestion
        omedaGraphQLClient,
```

2022-11-21 15:19 UTC, solocommand approved these changes

2022-11-21 16:53 UTC, merged